sales_order_schema = {
    "type": "record",
    "name": "SalesOrder",
    "fields": [{
        "name": "Buyer",
        "type": [{
            "type": "record",
            "name": "Buyer",
            "fields": [{
                "name": "address",
                "type": "string"
            }, {
                "name": "buyer_name",
                "type": "string"
            }, {
                "name": "email",
                "type": "string"
            }, {
                "name": "location",
                "type": "string"
            }, {
                "name": "phone_no",
                "type": "string"
            }, {
                "name": "tin_no",
                "type": "string"
            }, {
                "name": "vat_reg_no",
                "type": "string"
            }]
        }]
    }, {
        "name": "Delivery_info",
        "type": [{
            "type": "record",
            "name": "Delivery_info",
            "fields": [{
                "name": "Delivery_note_number",
                "type": "string"
            }, {
                "name": "delivery_address",
                "type": "string"
            }, {
                "name": "delivery_date",
                "type": "string"
            }, {
                "name": "delivery_location",
                "type": "string"
            }]
        }]
    }, {
        "name": "Order_line",
        "type": [{
            "type": "array",
            "items": ["null", {
                "type": "record",
                "name": "Order_line",
                "fields": [{
                    "name": "HSNcode",
                    "type": "string"
                }, {
                    "name": "Line_charge_amount",
                    "type": "string"
                }, {
                    "name": "Line_charge_code",
                    "type": "string"
                }, {
                    "name": "Line_charge_reason",
                    "type": "string"
                }, {
                    "name": "Product_Description",
                    "type": "string"
                }, {
                    "name": "Product_Name",
                    "type": "string"
                }, {
                    "name": "Product_price",
                    "type": "string"
                }, {
                    "name": "Product_qty",
                    "type": "string"
                }, {
                    "name": "Product_unit",
                    "type": "string"
                }, {
                    "name": "Total_Price",
                    "type": "string"
                }, {
                    "name": "sequence",
                    "type": "string"
                }, {
                    "name": "tax_amount",
                    "type": "string"
                }, {
                    "name": "tax_amount_type",
                    "type": "string"
                }, {
                    "name": "tax_scope",
                    "type": "string"
                }, {
                    "name": "tax_type",
                    "type": "string"
                }]
            }]
        }]
    }, {
        "name": "Sales_Order_Desc",
        "type": [{
            "type": "record",
            "name": "Sales_Order_Desc",
            "fields": [{
                "name": "Exchange_Title",
                "type": "string"
            }, {
                "name": "Order_deadline",
                "type": "string"
            }, {
                "name": "Receipt_Dt",
                "type": "string"
            }, {
                "name": "SO_no",
                "type": "string"
            }, {
                "name": "Sales_Order_Type",
                "type": "string"
            }]
        }]
    }, {
        "name": "Sales_Order_ref",
        "type": [{
            "type": "record",
            "name": "Sales_Order_ref",
            "fields": [{
                "name": "CAT_ref_no",
                "type": "string"
            }, {
                "name": "Customer_PO_ref_no",
                "type": "string"
            }, {
                "name": "Rec_advice_ref_no",
                "type": "string"
            }, {
                "name": "SO_State",
                "type": "string"
            }, {
                "name": "SO_ref_no",
                "type": "string"
            }]
        }]
    }, {
        "name": "Sales_total",
        "type": "string"
    }, {
        "name": "Seller",
        "type": [{
            "type": "record",
            "name": "Seller",
            "fields": [{
                "name": "address",
                "type": "string"
            }, {
                "name": "company_name",
                "type": "string"
            }, {
                "name": "email",
                "type": "string"
            }, {
                "name": "location",
                "type": "string"
            }, {
                "name": "phone_no",
                "type": "string"
            }, {
                "name": "tin_no",
                "type": "string"
            }, {
                "name": "vat_reg_no",
                "type": "string"
            }]
        }]
    }, {
        "name": "Vat_breakdown",
        "type": [{
            "type": "record",
            "name": "Vat_breakdown",
            "fields": [{
                "name": "Vat_breakdown_amount",
                "type": "string"
            }, {
                "name": "Vat_category_code",
                "type": "string"
            }, {
                "name": "Vat_reason_code",
                "type": "string"
            }, {
                "name": "Vat_reason_text",
                "type": "string"
            }]
        }]
    }]
}