{
    "name": "Addis Systems Base",
    "version": "16.0.1.0",
    "sequence": 1,
    "summary": "Addis Systems Base",
    "description": """
        This is a Base Module for Addis Systems Instances.
            ========================================
    """,
    "category": "Addis Systems/Base",
    "author": "Addis Systems/Beruk W.",
    "website": "https://www.addissystems.et/",
    "license": "LGPL-3",
    "depends": ["base", "web", "web_editor", "mail", "addis_systems_theme"],
    "external_dependencies": {},
    "data": [
        "data/AddisSystemsBaseRecordsInherit.xml",
        "data/AddisSystemsEthiopiaBanks.xml",
        "views/AddisSystemsUIConfiguration.xml",
        "views/AddisSystemsCompanyInheritedView.xml",
        "views/AddisSystemsPartnerInheritedView.xml",
        "views/AddisSystemsBankInheritedView.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [],
        "web._assets_backend_helpers": [],
        "web.assets_backend": [],
        "web.assets_frontend": [],
        "web.assets_tests": [],
        "web.qunit_suite_tests": [],
        "web.assets_qweb": [],
    },
    "demo": [],
    "pre_init_hook": "_pre_init_hook",
    "post_init_hook": "_post_init_hook",
    "installable": True,
    "price": 49.99,
    "currency": "ETB",
    "application": True,
    "auto_install": True,
}
